NurseriesGuide/NurseriesGuide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("main.urls")),
    path('nurseries/', include("nurseries.urls")),
    path('parents/', include("parents.urls")),
    path('registration/', include("registrations.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NurseriesGuide/main/urls.py
from django.urls import path
from . import views


app_name = "main"



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name='about_us'),
    path('staff/dashboard/',views.staff_dashboard,name="staff_dashboard"),
    path('admin-dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('contact/', views.contact_view, name="contact_view"),
    path('reviews/', views.add_review, name="add_review"),
    path('terms-of-use/', views.terms_of_use, name="terms_of_use"),
    

]

NurseriesGuide/nurseries/urls.py
from django.urls import path
from . import views


app_name = "nurseries"


urlpatterns = [
    path("view",views.nurseries_view,name="nurseries_view"),
    path("",views.nurseries_list,name="nurseries_list"),
    path("requests-admin/",views.verify_nurseries,name="verify_nurseries"),
    path("admin/statistics/",views.admin_nursery_statistics,name="admin_nursery_statistics"),


    path("owner/requests/",views.owner_requests_view,name="owner_requests_view"),
    path("statistics/",views.owner_nursery_statistics,name="owner_nursery_statistics"),

    path("chlidren/requests/", views.children_requests, name="children_requests"),

    path("add/",views.add_nursery,name="add_nursery"),
    path("update/<int:nursery_id>/",views.update_nursery,name="update_nursery"),
    path("delete/<int:nursery_id>/",views.delete_nursery,name="delete_nursery"),
    path("detail/<int:nursery_id>/",views.detail_nursery,name="nursery_detail"),

    path("add/<int:nursery_id>/activity",views.add_activity,name="add_activity"),
    path("update/<int:activity_id>/activity/",views.update_activity,name="update_activity"),
    path("delete/<int:activity_id>/activity/",views.delete_activity,name="delete_activity"),

    path("add/<int:nursery_id>/staff/",views.add_staff,name="add_staff"),
    path("update/<int:staff_id>/staff/",views.update_staff,name="update_staff"),
    path("delete/<int:staff_id>/staff/",views.delete_staff,name="delete_staff"),

    path("add/<int:nursery_id>/gallery/", views.add_gallery, name="add_gallery"),

    path("check-out/<int:child_id>/",views.check_out, name="check_out"),
    path('payment-success/<int:child_id>/', views.payment_success, name='payment_success'),
    path('payment-cancel/<int:child_id>/', views.payment_cancel, name='payment_cancel'),

    path('map', views.nursery_map, name="nursery_map")

]

NurseriesGuide/parents/urls.py
from django.urls import path
from . import views

app_name = "parents"

urlpatterns = [

    path('logout/', views.log_out, name="log_out"),
    path('add/', views.add_child, name="add_child"),
    path('delete/child/<int:child_id>', views.delete_child, name="delete_child"),
    path('update/child/<int:child_id>', views.update_child, name="update_child"),
    path('update/user/', views.update_user, name="update_user"),
    path('requests-status/', views.requests_status, name="requests_status"),
    path('signup/manager/', views.signup_manager, name="signup_manager"),
    path('signup/parent/', views.signup_parent, name="signup_parent"),
    path('signin/', views.signin, name="signin"),
    path('profile/', views.parent_profile, name="parent_profile"),



]

NurseriesGuide/registrations/urls.py
from django.urls import path
from . import views


app_name = "registrations"



urlpatterns = [
    path('create/', views.registration_create, name='registration_create'),

    path('<int:pk>/update-status/', views.registration_update_status, name='registration_update_status'),
    path('registration/add/subscription/<int:nursery_id>/', views.add_subscription, name='add_subscription'),
    
    path('delete/registration/<int:registration_id>/', views.delete_registration, name='delete_registration'),

    path('add/review/<int:nursery_id>/', views.add_review, name='add_review'),

    ]

NurseriesGuide/nurseries/models.py
from django.db import models
from django.contrib.auth.models import User
import re

# City Model
class City(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

# Neighborhood Model
class Neighborhood(models.Model):
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, related_name='neighborhoods', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.city.name},{self.name}"


# Nursery Model
class Nursery(models.Model):
    name = models.CharField(max_length=255)
    address = models.URLField(max_length=3000)  # Changed from CharField to URLField
    contact_number = models.CharField(max_length=15)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    accepts_special_needs = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    status = models.CharField(max_length=20, default='pending', choices=(
        ('pending', 'تحت المراجعه'),
        ('verified', 'موثق'),
        ('rejected', 'مرفوض')
    ))
    rejection_reason = models.TextField(blank=True, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, related_name='nurseries')

    owner = models.ForeignKey(User, on_delete=models.CASCADE,  limit_choices_to={'is_staff': True})

    commercial_registry_file = models.FileField(upload_to='commercial_registry/', null=True, blank=True)
    license_file = models.FileField(upload_to='nursery_licenses/', null=True, blank=True)

    min_age = models.PositiveIntegerField(default=1)
    max_age = models.PositiveIntegerField(default=5)
    # max_age_unit = models.CharField(max_length=10, choices=(('months', 'أشهر'), ('years', 'سنوات')), default='years')
    # min_age_unit = models.CharField(max_length=10, choices=(('months', 'أشهر'), ('years', 'سنوات')), default='years')
    main_image = models.ImageField(upload_to='images/', default="images/nursery_default.jpg")

    def get_lat_lng(self):
        match = re.search(r'loc:([-\d.]+),([-\d.]+)', self.location)
        if match:
            return match.group(1), match.group(2)
        return None, None


    def __str__(self):
        return self.name



#Activity Model
class Activity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    age_min = models.IntegerField(default=2)
    age_max = models.IntegerField(default=5)
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


#Gallery Model
class Gallery(models.Model):
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    nursery = models.ForeignKey('Nursery', on_delete=models.CASCADE)

#Staff Model
class Staff(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', default="images/profile_default.jpg")
    specializations = models.TextField()
    experience=models.TextField()
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

NurseriesGuide/parents/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, Http404
from django.core.paginator import Paginator
from django.contrib import messages
from django.db import IntegrityError , transaction
from django.contrib.auth.models import User
from nurseries.models import Nursery
from .models import Parent
from .models import Child
from .forms import ChildForm ,ParentForm
from registrations.models import Registration
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, EmailValidator
import re 

def signup_parent(request: HttpRequest):
    if request.method == "POST":
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        email = request.POST.get("email")
        phone_number = request.POST.get("phone_number")
        work_number = request.POST.get("Work_number")
        
        # Server-side validation
        error_message = None
        
        # Check if username already exists
        if User.objects.filter(username=username).exists():
            error_message = "اسم المستخدم موجود مسبقًا. يرجى اختيار اسم مستخدم آخر."
        
        # Check if email already exists
        if User.objects.filter(email=email).exists():
            error_message = "البريد الإلكتروني مستخدم مسبقًا. يرجى استخدام بريد إلكتروني آخر."
        
        # Validate username (only alphanumeric characters and underscores)
        if not error_message and (not username or not username.isalnum()):
            error_message = "اسم المستخدم يجب أن يحتوي فقط على أحرف إنجليزية وأرقام."
        
        # Validate first and last names (Arabic and English letters)
        name_regex = r'^[a-zA-Z\u0621-\u064A\u066E-\u066F]+$'
        if not error_message and not re.match(name_regex, first_name):
            error_message = "الاسم الأول يجب أن يحتوي فقط على أحرف عربية أو إنجليزية."
        elif not error_message and not re.match(name_regex, last_name):
            error_message = "الاسم الأخير يجب أن يحتوي فقط على أحرف عربية أو إنجليزية."

        # Validate password length and content
        if not error_message and len(password) < 8:
            error_message = "يجب أن تحتوي كلمة المرور على ٨ أحرف أو أرقام على الأقل."
        elif not error_message and not re.match(r'^(?=.*[0-9])(?=.*[a-zA-Z]).{8,}$', password):
            error_message = "يجب أن تحتوي كلمة المرور على أحرف وأرقام."
        elif not error_message and password != confirm_password:
            error_message = "كلمة المرور غير متطابقة."
        
        # Validate email format and domain
        if not error_message:
            email_validator = EmailValidator()
            allowed_domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'icloud.com']
            try:
                email_validator(email)
                domain = email.split('@')[-1]
                if domain not in allowed_domains:
                    error_message = "يجب أن يكون البريد الإلكتروني صحيحا وضمن الايميلات المسموح تسجيلها (gmail, hotmail, yahoo, outlook, icloud)."
            except ValidationError:
                error_message = "البريد الإلكتروني غير صحيح."
        
        # Validate phone numbers
        if not error_message:
            phone_regex = r'^05[0-9]{8}$'
            phone_validator = RegexValidator(phone_regex, message="رقم الهاتف يجب أن يبدأ بـ '05' ويليه 8 أرقام.")
            try:
                phone_validator(phone_number)
                phone_validator(work_number)
            except ValidationError:
                error_message = "رقم الهاتف أو رقم هاتف العمل غير صحيح."
        
        if error_message:
            # Pass the current POST data back to the template to preserve user input
            return render(request, "parents/sign_up_parent.html", {
                "username": username,
                "first_name": first_name,
                "last_name": last_name,
                "email": email,
                "phone_number": phone_number,
                "work_number": work_number,
                "password":password,
                "confirm_password":confirm_password,
                "error_message": error_message,
            })

        # If no validation errors, proceed to save user and profile
        try:
            with transaction.atomic():
                new_parent = User.objects.create_user(
                    username=username,
                    password=password,
                    email=email,
                    first_name=first_name,
                    last_name=last_name
                )
                profile = Parent(user=new_parent, Work_number=work_number, phone_number=phone_number)
                profile.save()
                login(request, new_parent)

            messages.success(request, "تم تسجيلك كولي امر بنجاح ", "alert-success")
            return redirect(request.GET.get("next", "/"))

        except IntegrityError:
            messages.error(request, "تم ادخال معلومات خاطئة ، ادخل  معلومات صحيحة", "alert-danger")
        except Exception as e:
            messages.error(request, "حدث خطأ غير متوقع يرجى المحاولة مرة أخرى", "alert-danger")
            print(e)

    return render(request, "parents/sign_up_parent.html")


def requests_status(request):
    if not request.user.is_authenticated or request.user.is_superuser or request.user.is_staff:
        return redirect("main:home")

    try:
        parent_obj = Parent.objects.get(user=request.user)
    except Parent.DoesNotExist:
        # Handle the case where the parent object does not exist
        return redirect("main:home")

    # Get all children related to the parent
    children = Child.objects.filter(parent=parent_obj)

    # Get all registration requests for the children
    registration_requests = Registration.objects.filter(child__in=children)

    context = {
        'status_choices': Registration.STATUS_CHOICES,
        'children': children,
        'registration_requests': registration_requests,
    }

    return render(request, 'parents/request_status.html', context)

def add_child(request:HttpRequest):

    if not request.user.is_authenticated:
        return redirect("main:home")  # Redirect non-authenticated users to home page

    parent = Parent.objects.get(user=request.user)

    if request.method == "POST":
        form = ChildForm(request.POST, request.FILES)
        if form.is_valid():
            child = form.save(commit=False)
            child.parent = parent 
            child.save()    
            messages.success(request, "تم إضافة الطفل بنجاح", 'alert-success')

        else:
            print(form.errors)
            messages.error(request,  "تم ادخال معلومات خاطئة ، ادخل  معلومات صحيحة", 'alert-danger')
        return redirect(request.GET.get("next", "/"))

    return render(request, 'parents/profile.html', {"gender": Child.GenderChoices.choices})

def update_user(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect("main:home")  # Redirect non-authenticated users to home page

    if request.method == "POST":
        try:
            with transaction.atomic():
                user:User = request.user

                user.first_name = request.POST["first_name"]
                user.last_name = request.POST["last_name"]
                user.email = request.POST["email"]
                user.username = request.POST["username"]
                user.save()
                if not (request.user.is_superuser or request.user.is_staff ):

                    if "phone_number" or "Work_number" in request.POST:
                        parent:Parent = user.parent
                        parent.phone_number = request.POST["phone_number"]
                        parent.Work_number = request.POST["Work_number"]
                        parent.save()

            messages.success(request, "تم تحديث البيانات بنجاح", 'alert-success')

        except Exception as e:
            messages.error(request, "تم إدخال معلومات خاطئة، أدخل معلومات صحيحة", 'alert-danger')
            print("error",e)
        return redirect(request.GET.get("next", "/"))

def delete_child(request:HttpRequest,child_id):

    if not request.user.is_authenticated:
        return redirect("main:home")  # Redirect non-authenticated users to home page

    child = Child.objects.get(pk=child_id)

    if child.delete():
        messages.success(request, f'بنجاح{child.first_name}تم ازالة معلومات ',"alert-success")
    
    else:
        messages.error(request, f"{child.first_name} لم نتمكن من ازالة معلومات","alert-danger")    

    return redirect(request.GET.get("next", "/"))


def update_child(request:HttpRequest,child_id):

    if not request.user.is_authenticated:
        return redirect("main:home")  # Redirect non-authenticated users to home page

    # parent = Parent.objects.get(user=request.user)
    child = Child.objects.get(pk=child_id)

    if request.method == "POST":
        form = ChildForm(request.POST, request.FILES, instance=child)
        if form.is_valid():
            form.save()       
            messages.success(request, "تم إضافة الطفل بنجاح", 'alert-success')
        else:
            print(form.errors)
            messages.error(request,  "تم ادخال معلومات خاطئة ، ادخل  معلومات صحيحة", 'alert-danger')
        return redirect(request.GET.get("next", "/"))

    return render(request, 'parents/profile.html', {"gender": Child.GenderChoices.choices})

def signup_manager(request: HttpRequest):
    if request.method == "POST":
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        password = request.POST.get("password")

NurseriesGuide/parents/templates/parents/request_status.html
{% extends 'main/base.html'%}

{% block title %} طلباتي{% endblock %}



{% block hero %}

<section class="ylo-section-wrapper">
  <div class="d-flex justify-content-center">
    <h3 class="text-center text-purp py-5 mt-5"> طلباتي </h3>
    <!-- <pre>{{ registration_requests }}</pre>
    <p class="text-center text-muted">لديك {{ registration_requests|length }} طلبات تسجيل</p> -->
  </div>
</section>

{% endblock %}




{% block content %}

<style>
    .action-link {
        color: #f28b82;
        text-decoration: none;
        font-weight: bold;
    }

    .action-link:hover {
        color: #f9b3ad;
    }

    .action-link.accept {
        color: #28a745;
    }

    .action-link.reject {
        color: #dc3545;
    }

    .action-link.review {
        color: #daa549;
    }

    .rounded-card {
        border-radius: 1.5rem;
        overflow: hidden;
        border: dotted 2px #ccc;
    }
    .card-body {
        background-color: #fdfdfd;
    }

</style>


<div class="container-fluid">
    {% if registration_requests %}
    <div class="row mt-4">
        {% for request in registration_requests %}
        <div class="col-lg-4 col-md-6 mb-4 d-flex">
            <div class="card rounded-card w-100">
                <div class="card-body">

                    <h5 class="card-title mb-3 d-flex justify-content-center action-link">
                        <a class="action-link" href="{% url 'nurseries:nursery_detail' request.subscription.nursery.id %}">{{ request.subscription.nursery }}</a>
                    </h5>

                    <div class="row align-items-center">
                        <div class="col-auto">
                            <img src="{{ request.child.photo.url }}" class=" mt-2 mb-2 rounded" style="max-height: 70px;" alt="">
                        </div>
                        <div class="col d-flex justify-content-center mb-3">
                            <h6 class="mb-0 text-purp ms-auto text-center"> الطفل:  </h6>
                            <h6 class="mb-0 text-purp ms-auto text-center">  {{ request.child.first_name }} {{ request.child.last_name }}</h6>
                        </div>
                    </div>

                    <div class="d-flex justify-content-center flex-column">
                      <h6 class=" text-center "><strong>حالة الطلب :</strong> {{ request.get_status_display }}</h6>
                      {% if request.status == 'rejected' %}
                      <h6><strong>سبب الرفض:</strong> {{ request.rejection_reason }}</h6>
                      {% endif %}
                  </div>

                  <div class="d-flex justify-content-center mt-3">
                      <h6 class="card-title mb-3">
                          {% if request.status == 'reviewing' %}
                          <a data-bs-toggle="modal" data-bs-target="#deleteModal-{{ request.id }}" href="#" class="action-link reject">
                              إلغاء الطلب
                          </a>
                          {% elif request.status == 'rejected' %}
                          <a data-bs-toggle="modal" data-bs-target="#deleteModal-{{ request.id }}" href="#">
                              <span class="material-symbols-outlined">delete</span>
                          </a>
                          {% elif request.status == 'waiting_payment' %}
                          <a href="{% url 'nurseries:check_out' request.child.id %}" class="action-link accept">
                              ادفع الآن
                          </a>
                          {% endif %}
                      </h6>
                  </div>


                    <!-- Modal for Deletion Confirmation -->
                    <div class="modal fade" id="deleteModal-{{ request.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ request.id }}" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                <h5 class="modal-title ms-auto text-pink" id="deleteModalLabel-{{ request.id }}">تأكيد الالغاء </h5>

                                </div>
                                <div class="modal-body text-center text-white">
                                    هل انت متاكد من الغاء طلب تسجيل "{{ request.child.first_name }}"؟
                                </div>
                                <div class="modal-footer justify-content-center">
                                  <button type="button" class="btn btn-warning rounded-pill" data-bs-dismiss="modal">تراجع</button>
                                  <a href="{% url 'registrations:delete_registration' request.id %}?next={{ request.path }}" class="btn btn-danger rounded-pill">الغاء الطلب</a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% else %}
    <div class="col-12 text-center">
      <div class="d-flex flex-column align-items-center">
          <div style="width: 100px; height: 100px;">
              <svg
                  height="100%"
                  stroke-miterlimit="10"
                  style="fill-rule:nonzero;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;"
                  version="1.1"
                  viewBox="4.21966 -0.000301042 458.837 467.277"
                  width="100%"
                  xml:space="preserve"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:vectornator="http://vectornator.io"
                  xmlns:xlink="http://www.w3.org/1999/xlink">
                  <defs/>
                  <clipPath id="ArtboardFrame">
                      <rect height="467.277" width="458.837" x="4.21966" y="-0.000301042"/>
                  </clipPath>
                  <g clip-path="url(#ArtboardFrame)" id="Layer" vectornator:layerName="Layer">
                      <g opacity="1" vectornator:layerName="g">
                          <path
                              d="M379.284 51.144C348.258 24.297 309.568 13.46 269.579 8.672C163.069-25.3 68.062 44.959 26.578 142.38C-18.134 247.382 3.143 364.597 100.094 430.078C199.074 496.924 335.116 469.447 411.036 381.451C494.021 285.274 473.541 132.719 379.284 51.144ZM196.853 432.703C140.696 424.71 86.217 390.16 57.762 340.898C32.324 296.851 32.537 241.695 43.942 193.586C61.469 119.626 114.508 52.876 183.828 36.9C183.932 36.905 184.021 36.935 184.125 36.935C209.068 37.674 235.416 37.717 261.17 40.502C263.608 41.266 266.045 42.025 268.503 42.922C272.561 44.402 276.114 44.212 279.085 42.993C306.872 47.67 333.404 56.572 356.042 74.385C406.121 113.79 432.521 184.846 431.074 247.081C428.353 364.389 307.974 448.516 196.853 432.703Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M169.279 211.913C192.559 211.913 192.559 175.809 169.279 175.809C145.999 175.808 145.999 211.913 169.279 211.913Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M293.832 213.715C317.119 213.715 317.119 177.613 293.832 177.613C270.555 177.613 270.555 213.715 293.832 213.715Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M134.855 300.254C117.821 316.189 143.404 341.665 160.387 325.781C203.689 285.284 259.489 280.998 302.738 323.978C319.262 340.4 344.8 314.878 328.265 298.446C270.92 241.467 192.476 246.372 134.855 300.254Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                      </g>
                  </g>
              </svg>
          </div>
          <p class="text-center fs-5 text-muted mt-3">لا يوجد طلبات تسجيل لأطفالك</p>
      </div>
  </div>

    {% endif %}
</div>

{% endblock %}

NurseriesGuide/parents/templates/parents/sign_in.html
{% extends 'main/base.html'%}


{% block title %} تسجيل دخول{% endblock %}

{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center gap-3">

    <h2>تسجيل الدخول</h2>
    <form class="d-flex flex-column gap-3 w-50 mb-3" action="{% url 'parents:signin' %}{% if 'next' in request.GET %}?next={{request.GET.next}}{% endif %}" method="POST">
        {% csrf_token %}
        

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="username" name="username">
            <label for="floatingInput">اسم المستخدم</label>
        </div>


        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
          <label for="floatingPassword">كلمة المرور</label>
        </div>
    

        <button class="btn btn-outline-pink w-100 py-2" type="submit">سجل الدخول</button>
      </form>
      <h5>ليس لديك حساب ؟ <a href="{% url 'parents:signup_parent' %}"> سجل كولي امر</a> او <a
        href="{% url 'parents:signup_manager' %}"> سجل كمالك حضانة</a></h5>
    </div>

{% endblock %}