NurseriesGuide/NurseriesGuide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("main.urls")),
    path('nurseries/', include("nurseries.urls")),
    path('parents/', include("parents.urls")),
    path('registration/', include("registrations.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NurseriesGuide/main/urls.py
from django.urls import path
from . import views


app_name = "main"



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name='about_us'),
    path('staff/dashboard/',views.staff_dashboard,name="staff_dashboard"),
    path('admin-dashboard/',views.admin_dashboard,name="admin_dashboard"),
    path('contact/', views.contact_view, name="contact_view"),
    path('reviews/', views.add_review, name="add_review"),
    path('terms-of-use/', views.terms_of_use, name="terms_of_use"),
    

]

NurseriesGuide/nurseries/urls.py
from django.urls import path
from . import views


app_name = "nurseries"


urlpatterns = [
    path("view",views.nurseries_view,name="nurseries_view"),
    path("",views.nurseries_list,name="nurseries_list"),
    path("requests-admin/",views.verify_nurseries,name="verify_nurseries"),
    path("admin/statistics/",views.admin_nursery_statistics,name="admin_nursery_statistics"),


    path("owner/requests/",views.owner_requests_view,name="owner_requests_view"),
    path("statistics/",views.owner_nursery_statistics,name="owner_nursery_statistics"),

    path("chlidren/requests/", views.children_requests, name="children_requests"),

    path("add/",views.add_nursery,name="add_nursery"),
    path("update/<int:nursery_id>/",views.update_nursery,name="update_nursery"),
    path("delete/<int:nursery_id>/",views.delete_nursery,name="delete_nursery"),
    path("detail/<int:nursery_id>/",views.detail_nursery,name="nursery_detail"),

    path("add/<int:nursery_id>/activity",views.add_activity,name="add_activity"),
    path("update/<int:activity_id>/activity/",views.update_activity,name="update_activity"),
    path("delete/<int:activity_id>/activity/",views.delete_activity,name="delete_activity"),

    path("add/<int:nursery_id>/staff/",views.add_staff,name="add_staff"),
    path("update/<int:staff_id>/staff/",views.update_staff,name="update_staff"),
    path("delete/<int:staff_id>/staff/",views.delete_staff,name="delete_staff"),

    path("add/<int:nursery_id>/gallery/", views.add_gallery, name="add_gallery"),

    path("check-out/<int:child_id>/",views.check_out, name="check_out"),
    path('payment-success/<int:child_id>/', views.payment_success, name='payment_success'),
    path('payment-cancel/<int:child_id>/', views.payment_cancel, name='payment_cancel'),

    path('map', views.nursery_map, name="nursery_map")

]

NurseriesGuide/registrations/urls.py
from django.urls import path
from . import views


app_name = "registrations"



urlpatterns = [
    path('create/', views.registration_create, name='registration_create'),

    path('<int:pk>/update-status/', views.registration_update_status, name='registration_update_status'),
    path('registration/add/subscription/<int:nursery_id>/', views.add_subscription, name='add_subscription'),
    
    path('delete/registration/<int:registration_id>/', views.delete_registration, name='delete_registration'),

    path('add/review/<int:nursery_id>/', views.add_review, name='add_review'),

    ]

NurseriesGuide/nurseries/models.py
from django.db import models
from django.contrib.auth.models import User
import re

# City Model
class City(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

# Neighborhood Model
class Neighborhood(models.Model):
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, related_name='neighborhoods', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.city.name},{self.name}"


# Nursery Model
class Nursery(models.Model):
    name = models.CharField(max_length=255)
    address = models.URLField(max_length=3000)  # Changed from CharField to URLField
    contact_number = models.CharField(max_length=15)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    accepts_special_needs = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    status = models.CharField(max_length=20, default='pending', choices=(
        ('pending', 'تحت المراجعه'),
        ('verified', 'موثق'),
        ('rejected', 'مرفوض')
    ))
    rejection_reason = models.TextField(blank=True, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, related_name='nurseries')

    owner = models.ForeignKey(User, on_delete=models.CASCADE,  limit_choices_to={'is_staff': True})

    commercial_registry_file = models.FileField(upload_to='commercial_registry/', null=True, blank=True)
    license_file = models.FileField(upload_to='nursery_licenses/', null=True, blank=True)

    min_age = models.PositiveIntegerField(default=1)
    max_age = models.PositiveIntegerField(default=5)
    # max_age_unit = models.CharField(max_length=10, choices=(('months', 'أشهر'), ('years', 'سنوات')), default='years')
    # min_age_unit = models.CharField(max_length=10, choices=(('months', 'أشهر'), ('years', 'سنوات')), default='years')
    main_image = models.ImageField(upload_to='images/', default="images/nursery_default.jpg")

    def get_lat_lng(self):
        match = re.search(r'loc:([-\d.]+),([-\d.]+)', self.location)
        if match:
            return match.group(1), match.group(2)
        return None, None


    def __str__(self):
        return self.name



#Activity Model
class Activity(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    age_min = models.IntegerField(default=2)
    age_max = models.IntegerField(default=5)
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


#Gallery Model
class Gallery(models.Model):
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    video = models.FileField(upload_to='videos/', blank=True, null=True)
    nursery = models.ForeignKey('Nursery', on_delete=models.CASCADE)

#Staff Model
class Staff(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', default="images/profile_default.jpg")
    specializations = models.TextField()
    experience=models.TextField()
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

NurseriesGuide/parents/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


class Parent(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=13) # 9665555555555 
    Work_number = models.CharField(max_length=13)

    def __str__(self):
        return f"{self.user.username} profile"
    

class Child(models.Model):

    class GenderChoices(models.TextChoices):
        
        FEMALE = "F", "انثى"
        MALE = "M", "ذكر"

    gender = models.CharField(
        max_length=1,
        choices=GenderChoices.choices,
    )

    first_name = models.CharField(max_length=124,default=None)
    last_name = models.CharField(max_length=124,default=None)
    birth_date = models.DateField()
    national_id = models.CharField(max_length=10)
    about = models.TextField(blank=True, default='')  
    Disease = models.TextField(blank=True, default='لايوجد') 
    Allergy = models.TextField(blank=True, default='لا يوجد') 
    parent = models.ForeignKey(Parent,on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="images/", default="images/default.jpg")

    def age(self):
        today = date.today()
        years = today.year - self.birth_date.year
        months = today.month - self.birth_date.month

        # التحقق مما إذا كان اليوم الحالي أقل من يوم الميلاد
        if today.day < self.birth_date.day:
            months -= 1

        # إذا كانت الأشهر سالبة، قم بتصحيح السنة والشهر
        if months < 0:
            years -= 1
            months += 12

        # إذا كان العمر أقل من سنة، أرجع عدد الأشهر فقط
        if years == 0:
            return f"{months} أشهر"
        else:
            return f"{years} سنة"
    def age_in_months(self):
        today = date.today()
        years = today.year - self.birth_date.year
        months = today.month - self.birth_date.month
        days = today.day - self.birth_date.day

        total_months = years * 12 + months
        if days < 0:
            total_months -= 1

        return total_months

NurseriesGuide/nurseries/forms.py
from django import forms
from .models import Nursery,Activity,Staff,Gallery

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"
        exclude = ['nursery'] 

class StaffForm(forms.ModelForm):

    class Meta:
        model = Staff
        fields = "__all__"
        exclude = ['nursery'] 
class GalleryForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = "__all__"
        exclude = ['nursery'] 
class NurseryOwnerForm(forms.ModelForm):
    class Meta:
        model = Nursery
        fields = "__all__"
        exclude = ['owner', 'status']  # Exclude both owner and status fields

class NurseryForm(forms.ModelForm):
    class Meta:
        model = Nursery
        fields = "__all__"
        exclude = ['owner'] 
        widgets = {
            'neighborhood': forms.HiddenInput(),
        }

NurseriesGuide/nurseries/templates/nurseries/children_requests.html
{% extends 'main/staff_dashboard.html' %}
{% load static %}

{% block title %}طلبات تسجيل الاطفال{% endblock %}

{% block Dashboard-content %}
<link href="{% static 'css/main.css' %}?v=1.1" rel="stylesheet" />
<style>
    .modal-content {
        background-color: #FFF3F4;
    }
</style>



<div class=" p-3 mt-5 mb-5  rounded" style="background-color: #fff;">
    {% if registrations %}
        <table class="table table-striped mt-3" >
            <thead>
                <tr>
                    <th style="background-color: #fff; color: #34366D;">تعديل الحاله</th>
                    <th style="background-color: #fff; color: #34366D;">حذف من السجل</th>
                    <th style="background-color: #fff; color: #34366D;">ملف الطفل</th>
                    <th style="background-color: #fff; color: #34366D;">الحضانه </th>
                    <th style="background-color: #fff; color: #34366D;">الخطه</th>
                    <th style="background-color: #fff; color: #34366D;">حاله الطلب</th>
                    <th style="background-color: #fff; color: #34366D;">تاريخ الطلب</th>
                </tr>
            </thead>
            <tbody>
                {% for registration in registrations %}
                <tr>
                    <td>
                        <a href="#" data-bs-toggle="modal" data-bs-target="#editModal-{{ registration.id }}">
                            <span class="material-symbols-outlined">تعديل</span>
                        </a>
                    </td>
                    <td>
                        <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal-{{ registration.id }}">
                            <span class="material-symbols-outlined">حذف</span>
                        </a>
                    </td>
                    <td>
                        <a href="#" data-bs-toggle="modal" data-bs-target="#ViewChildyModal-{{ registration.child.id }}" style="text-decoration: none; color: inherit;">
                            {{ registration.child.first_name }} {{ registration.child.last_name }}
                        </a>
                    </td>
                    <td >{{ registration.subscription.nursery.name }} </td>
                    <td>
                        {{ registration.subscription.duration_number }} {{ registration.subscription.get_duration_unit_display }}

                    </td>
                    <td>{{registration.get_status_display}} </td>
                   <td>{{ registration.created_at|date:"Y-m-d" }}</td>
                </tr>
                <!-- Modal for Registration Status Update -->
                <div class="modal fade" id="editModal-{{ registration.id }}" tabindex="-1" aria-labelledby="editModalLabel-{{ registration.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                <h5 class="modal-title text-pink ms-auto" id="editModalLabel-{{ registration.id }}">تحديث حالة التسجيل</h5>
                            </div>
                            <div class="modal-body">
                                <form method="post" action="{% url 'registrations:registration_update_status' registration.id %}">
                                    {% csrf_token %}
                                    <div class="text-end">
                                    <label for="status-{{ registration.id }}" class="form-label text-white">حالة التسجيل</label>
                                    <select class="form-control mb-3" id="status-{{ registration.id }}" name="status" required>
                                        {% for status, status_display in registration.STATUS_CHOICES %}
                                            <option value="{{ status }}" {% if registration.status == status %}selected{% endif %}>

                                                    {{ status_display }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                  </div>

                                  <div class="text-end">
                                    <label for="rejection-reason-{{ registration.id }}" class="form-label text-white">سبب الرفض (اختياري)</label>
                                    <textarea class="form-control mb-3" id="rejection-reason-{{ registration.id }}" name="rejection_reason">{{ registration.rejection_reason }}</textarea>
                                    <div class="d-flex justify-content-center mt-4">
                                        <button type="submit" class="btn btn-dark rounded-pill">أحفظ التعديلات</button>
                                    </div>
                                  </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal for Registration Deletion Confirmation -->
                <div class="modal fade" id="deleteModal-{{ registration.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ registration.id }}" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                <h5 class="modal-title text-pink ms-auto" id="deleteModalLabel-{{ nursery.id }}">تأكيد الحذف  </h5>

                            </div>
                            <div class="modal-body text-white text-center">
                              هل انت متاكد من حذف طلب
                              {{ registration.child.first_name }} {{ registration.child.last_name }}؟
                            </div>
                            <div class="modal-footer justify-content-center">
                              <button type="button" class="btn btn-warning rounded-pill" data-bs-dismiss="modal">تراجع</button>
                                <a href="{% url 'registrations:delete_registration' registration.id %}" class="btn btn-danger rounded-pill">حذف</a>
                            </div>
                        </div>
                    </div>
                </div>
                    <!-- #ViewChildyModal -->
                    <div class="modal fade" id="ViewChildyModal-{{ registration.child.id }}" tabindex="-1" aria-labelledby="ViewChildyModal-{{ registration.child.id }}" aria-hidden="true">                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content" style="background-color:  #FFF3F4;">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="updateModalLabel-{{ registration.child.first_name }}">عرض بيانات  </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">

                                    <div class="child-info">

                                        <div class="d-flex flex-column justify-content-center align-items-center">

                                            <img src="{{registration.child.photo.url}}" class="w-25 rounded-circle"/>

                                            <h2>{{ registration.child.first_name }} {{registration.child.last_name}}</h2>


                                        </div>

                                        <h4>الهوية : {{registration.child.national_id}}</h4>
                                        <h4>نبذة عن الطفل : {{registration.child.about}}</h4>
                                        <h4>العمر : {{registration.child.age}} </h4>
                                        <h4>الجنس : {{registration.child.get_gender_display}}</h4>
                                        <h4>الامراض : {{registration.child.Disease}}</h4>
                                        <h4>الحساسية : {{registration.child.Allergy}}</h4>



                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>



                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <div class="col-12 text-center">
      <div class="d-flex flex-column align-items-center">
          <div style="width: 100px; height: 100px;">
              <svg
                  height="100%"
                  stroke-miterlimit="10"
                  style="fill-rule:nonzero;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;"
                  version="1.1"
                  viewBox="4.21966 -0.000301042 458.837 467.277"
                  width="100%"
                  xml:space="preserve"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:vectornator="http://vectornator.io"
                  xmlns:xlink="http://www.w3.org/1999/xlink">
                  <defs/>
                  <clipPath id="ArtboardFrame">
                      <rect height="467.277" width="458.837" x="4.21966" y="-0.000301042"/>
                  </clipPath>
                  <g clip-path="url(#ArtboardFrame)" id="Layer" vectornator:layerName="Layer">
                      <g opacity="1" vectornator:layerName="g">
                          <path
                              d="M379.284 51.144C348.258 24.297 309.568 13.46 269.579 8.672C163.069-25.3 68.062 44.959 26.578 142.38C-18.134 247.382 3.143 364.597 100.094 430.078C199.074 496.924 335.116 469.447 411.036 381.451C494.021 285.274 473.541 132.719 379.284 51.144ZM196.853 432.703C140.696 424.71 86.217 390.16 57.762 340.898C32.324 296.851 32.537 241.695 43.942 193.586C61.469 119.626 114.508 52.876 183.828 36.9C183.932 36.905 184.021 36.935 184.125 36.935C209.068 37.674 235.416 37.717 261.17 40.502C263.608 41.266 266.045 42.025 268.503 42.922C272.561 44.402 276.114 44.212 279.085 42.993C306.872 47.67 333.404 56.572 356.042 74.385C406.121 113.79 432.521 184.846 431.074 247.081C428.353 364.389 307.974 448.516 196.853 432.703Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M169.279 211.913C192.559 211.913 192.559 175.809 169.279 175.809C145.999 175.808 145.999 211.913 169.279 211.913Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M293.832 213.715C317.119 213.715 317.119 177.613 293.832 177.613C270.555 177.613 270.555 213.715 293.832 213.715Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                          <path
                              d="M134.855 300.254C117.821 316.189 143.404 341.665 160.387 325.781C203.689 285.284 259.489 280.998 302.738 323.978C319.262 340.4 344.8 314.878 328.265 298.446C270.92 241.467 192.476 246.372 134.855 300.254Z"
                              fill="#F5888E"
                              fill-rule="nonzero"
                              opacity="1"
                              stroke="none"
                              vectornator:layerName="path"/>
                      </g>
                  </g>
              </svg>
          </div>
          <p class="text-center fs-5 text-muted mt-3">لا يوجد طلبات تسجيل</p>
      </div>
  </div>
    {% endif %}
</div>
{% endblock %}

NurseriesGuide/nurseries/templates/nurseries/superuser_nurseries.html
{% extends 'main/admin_dashboard.html' %}
{% load static %}

{% block title %}طلبات الحضانات{% endblock %}

{% block Dashboard-content %}
<link href="{% static 'css/main.css' %}?v=1.1" rel="stylesheet" />

<style>
    .rounded-card {
        border-radius: 1.5rem;
        overflow: hidden;
        border: dotted 2px #ccc;
    }
    .card-body {
        background-color: #fdfdfd;
    }
    .form-section {
        margin-top: 20px;
    }
    .action-link {
        color: #343779;
        text-decoration: none;
        font-weight: bold;
    }

    .action-link:hover {
        color: #f28b82;
    }

    .action-link.accept {
        color: #28a745;
    }

    .action-link.reject {
        color: #dc3545;
    }


</style>

<h3 class="mt-4 text-end text-purp">حضانات تحتاج الى توثيق</h3>


<div class="container-fluid mt-5">
    <div class="row mt-4">
        {% for nursery in unverified_nurseries %}
        <div class="col-md-4 col-sm-6 mb-4">
            <div class="card rounded-card">
                <div class="card-body">
                    <h5 class="card-title mb-3 text-center text-purp">
                        <a href="{% url 'nurseries:nursery_detail' nursery.id %}">تفاصيل {{ nursery.name }}</a>
                    </h5>


                    <div class="location-container d-flex justify-content-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#f28b82" class="bi bi-geo-alt location-icon" viewBox="0 0 16 16">
                            <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                            <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        </svg>
                        <h6 class="text-center text-muted location-text">{{ nursery.neighborhood }}</h6>
                    </div>

                    <div class="d-flex justify-content-center mb-3 mt-4">
                        <a class="action-link" href="{{ nursery.commercial_registry_file.url }}" target="_blank">سجل تجاري</a>
                        <a class="action-link me-3" href="{{ nursery.license_file.url }}" target="_blank">رخصة</a>
                    </div>

                    <div class="form-section d-flex justify-content-center">
                        <form method="post" action="{% url 'nurseries:verify_nurseries' %}">
                            {% csrf_token %}
                            <input type="hidden" name="nursery_id" value="{{ nursery.id }}">
                            <a href="javascript:;" onclick="parentNode.submit();" class="action-link accept" name="action" value="verify">قبول</a>
                            <a href="#" class="action-link reject me-3" data-bs-toggle="modal" data-bs-target="#rejectionModal-{{ nursery.id }}">رفض</a>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Rejection Modal -->
            <div class="modal fade" id="rejectionModal-{{ nursery.id }}" tabindex="-1" role="dialog" aria-labelledby="rejectionModalLabel-{{ nursery.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                <h5 class="modal-title text-pink ms-auto" id="rejectionModalLabel-{{ nursery.id }}"> سبب الرفض</h5>

                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="post" action="{% url 'nurseries:verify_nurseries' %}">
                            {% csrf_token %}
                            <div class="modal-body">
                                <input type="hidden" name="nursery_id" value="{{ nursery.id }}">
                                <textarea name="rejection_reason" placeholder="ادخل السبب" class="form-control"></textarea>
                            </div>
                                <div class="modal-footer justify-content-center">
                                <button type="button" class="btn btn-warning rounded-pill" data-dismiss="modal">تراجع</button>
                                <button type="submit" name="action" value="reject" class="btn btn-danger rounded-pill"> تأكيد الرفض</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="d-flex justify-content-center">


          <div class="col-12 text-center">
            <div class="d-flex flex-column align-items-center">
                <div class="py-3 align-items-center" style="width: 100px; height: 100px; padding-left: 13%;">
                  <svg height="150px" width="150px" stroke-miterlimit="10" style="fill-rule:nonzero;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;" version="1.1" viewBox="-0.00117167 10.7462 482.822 461.329" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g opacity="1">
                        <path d="M475.743 177.824C473.483 174.932 470 172.941 465.216 172.941L315.293 172.941C295.245 122.538 274.796 72.308 258.517 20.523C253.672 5.104 231.466 9.446 230.831 22.976C207.477 72.811 186.043 123.375 173.569 177.07C120.215 176.732 66.896 174.506 13.539 174.345C-2.675 174.297-4.308 196.767 8.537 201.482C47.63 237.31 88.916 270.449 133.869 298.641C119.049 348.959 102.893 398.835 85.582 448.356C82.411 457.43 88.54 463.696 95.878 465.103C99.549 467.336 104.218 467.601 108.986 464.194C152.431 433.168 197.051 403.842 240.991 373.516C285.418 406.162 328.85 440.134 375.375 469.805C385.688 476.386 395.402 467.489 396.007 458.024C396.52 455.962 396.601 453.677 395.982 451.159C383.698 401.177 369.256 351.935 347.076 305.482C394.804 274.978 433.412 233.092 477.94 198.291C486.29 191.765 482.836 182.326 475.743 177.824ZM323.474 287.079C320.514 288.826 318.64 291.121 317.634 293.625C315.136 297.469 314.364 302.466 317.04 307.676C336.437 345.471 349.615 385.531 360.608 426.338C323.214 400.612 287.313 372.806 250.661 345.994C249.614 345.232 248.579 344.694 247.553 344.267C243.773 341.626 238.801 341.047 233.696 344.592C197.787 369.515 161.35 393.676 125.41 418.547C138.778 378.853 151.399 338.93 163.124 298.717C164.995 292.294 162.479 287.251 158.325 284.296C157.373 281.625 155.527 279.147 152.468 277.258C116.836 255.295 83.733 230.096 52.186 202.85C94.942 203.609 137.691 205.074 180.46 205.206C181.691 205.211 182.826 205.059 183.898 204.82C190.106 205.718 196.527 202.901 198.197 194.908C207.764 149.001 224.247 105.647 243.206 63.099C258.125 105.632 275.172 147.378 291.787 189.3C291.838 189.434 291.914 189.533 291.97 189.663C292.986 195.675 297.429 200.999 305.31 200.999L430.959 200.999C396.226 231.168 363.346 263.512 323.474 287.079Z" fill="#f5888e" fill-rule="nonzero" opacity="1" stroke="none"/>
                        <path d="M250.514 134.473C247.929 126.267 236.11 128.575 235.778 135.778C223.344 162.308 211.934 189.221 205.295 217.805C176.899 217.627 148.513 216.437 120.112 216.353C111.48 216.328 110.611 228.289 117.448 230.8C138.253 249.868 160.233 267.508 184.163 282.519C176.274 309.305 167.675 335.858 158.461 362.212C156.77 367.047 160.035 370.378 163.945 371.129C165.895 372.317 168.386 372.46 170.925 370.651C194.048 354.128 217.802 338.518 241.189 322.38C264.839 339.757 287.96 357.839 312.725 373.632C318.219 377.13 323.383 372.398 323.708 367.361C323.982 366.264 324.028 365.046 323.698 363.705C317.158 337.106 309.469 310.884 297.668 286.164C323.073 269.925 343.624 247.623 367.323 229.098C371.771 225.625 369.933 220.602 366.155 218.206C364.951 216.665 363.103 215.606 360.549 215.606L280.743 215.606C270.064 188.78 259.182 162.042 250.514 134.473Z" fill="#f5888e" fill-rule="nonzero" opacity="1" stroke="none"/>
                    </g>
                  </svg>
                </div>
                <div>
                  <p class="text-center fs-5 text-muted mt-5 py-5">لا توجد حضانات غير موثقه</p>
                </div>

            </div>
        </div>

        {% endfor %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}